# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:07
from __future__ import unicode_literals

import boards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(default=boards.models.generate_board_id, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('path', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boards', models.ManyToManyField(to='boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=boards.models.generate_post_id, max_length=11, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=65536)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QsRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('params', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=500)),
                ('repl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(default=boards.models.generate_site_id, max_length=7, primary_key=True, serialize=False)),
                ('netloc', models.URLField(db_index=True, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(default=boards.models.generate_thread_id, max_length=11, primary_key=True, serialize=False)),
                ('raw_path', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='boards.Board')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rerule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_rules', to='boards.Site'),
        ),
        migrations.AddField(
            model_name='qsrule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_rules', to='boards.Site'),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.Site'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boards.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.Thread'),
        ),
        migrations.AddField(
            model_name='board',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='boards.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='qsrule',
            unique_together=set([('site', 'path')]),
        ),
        migrations.AlterIndexTogether(
            name='qsrule',
            index_together=set([('site', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('site', 'path')]),
        ),
        migrations.AlterIndexTogether(
            name='board',
            index_together=set([('site', 'path')]),
        ),
    ]
