# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.Post'),
        ),
    ]
