# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '__first__'),
        ('boards', '0004_auto_20170328_2348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='vote',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='vote_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='votes.VoteEntity'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
