# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 19:09
from __future__ import unicode_literals

from django.db import migrations


def set_vote_entities(apps, schema_editor):
    VoteEntity = apps.get_model('votes', 'VoteEntity')
    Post = apps.get_model('boards', 'Post')
    for post in Post.objects.all():
        post.vote_entity = VoteEntity.objects.create()
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20170410_2109'),
    ]

    operations = [
        migrations.RunPython(set_vote_entities),
    ]
