# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:07
from __future__ import unicode_literals

from django.db import migrations


def set_original_post(apps, schema_editor):
    Post = apps.get_model('boards', 'Post')
    for post in Post.objects.select_related('thread').filter(parent=None):
        post.thread.original_post = post
        post.thread.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_thread_original_post'),
    ]

    operations = [
        migrations.RunPython(set_original_post),
    ]
