# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20170418_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='netloc',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
