# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20170430_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rerule',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='qs_rules',
            field=models.ManyToManyField(related_name='sites', to='boards.QsRule'),
        ),
        migrations.AddField(
            model_name='site',
            name='re_rules',
            field=models.ManyToManyField(related_name='sites', to='boards.ReRule'),
        ),
        migrations.AlterUniqueTogether(
            name='qsrule',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='qsrule',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='qsrule',
            name='site',
        ),
    ]
