# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170423_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmuser',
            name='ext_picture_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
