# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cmuser_ext_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmuser',
            name='uid',
            field=models.CharField(default=b'1', max_length=11),
        ),
    ]
