# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 21:28
from __future__ import unicode_literals

import string
from random import choice

from django.db import migrations


def random_id(model, size, field_name='id'):
    chars = string.ascii_letters + string.digits + '_-'
    while True:
        mid = ''.join(choice(chars) for _ in range(size))
        kwargs = {field_name: mid}
        if not model.objects.filter(**kwargs).exists():
            break
    return mid


def set_uids(apps, schema_editor):
    User = apps.get_model('authentication', 'CMUser')
    for user in User.objects.all():
        user.uid = random_id(User, 11, field_name='uid')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_cmuser_uid'),
    ]

    operations = [
        migrations.RunPython(set_uids),
    ]
