# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 21:28
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170512_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmuser',
            name='uid',
            field=models.CharField(default=authentication.models.generate_user_id, max_length=11, unique=True),
        ),
    ]
